

using UnityEngine;


//
// Autogenerated by gaxb ( https://github.com/SmallPlanet/gaxb )
//

using System;
using System.Xml;
using System.Text;
using System.Reflection;
using System.Collections.Generic;
using System.Collections;


public partial class PUScrollRect : PUScrollRectBase {
	
	public PUScrollRect()
	{
		string attr;

		attr = "true";
		if(attr != null) { inertia = bool.Parse(attr); } 
		attr = "false";
		if(attr != null) { horizontal = bool.Parse(attr); } 
		attr = "true";
		if(attr != null) { vertical = bool.Parse(attr); } 
		attr = "0";
		if(attr != null) { scrollWheelSensitivity = float.Parse(attr); } 

	}
	
	
	public PUScrollRect(
			bool inertia,
			bool horizontal,
			bool vertical,
			float scrollWheelSensitivity ) : this()
	{
		this.inertia = inertia;

		this.horizontal = horizontal;

		this.vertical = vertical;

		this.scrollWheelSensitivity = scrollWheelSensitivity;
	}

	
	
	public PUScrollRect(
			bool inertia,
			bool horizontal,
			bool vertical,
			float scrollWheelSensitivity,
			Vector4 bounds,
			Vector3 position,
			Vector2 size,
			Vector3 rotation,
			Vector3 scale,
			Vector2 pivot,
			string anchor,
			bool active,
			bool mask,
			Vector4 maskInset,
			bool outline,
			float lastY,
			float lastX,
			string shader,
			bool ignoreMouse,
			string components,
			string title,
			string tag,
			string tag1,
			string tag2,
			string tag3,
			string tag4,
			string tag5,
			string tag6 ) : this()
	{
		this.inertia = inertia;

		this.horizontal = horizontal;

		this.vertical = vertical;

		this.scrollWheelSensitivity = scrollWheelSensitivity;

		this.bounds = bounds;

		this.position = position;

		this.size = size;

		this.rotation = rotation;

		this.scale = scale;

		this.pivot = pivot;

		this.anchor = anchor;

		this.active = active;

		this.mask = mask;

		this.maskInset = maskInset;

		this.outline = outline;

		this.lastY = lastY;

		this.lastX = lastX;

		this.shader = shader;

		this.ignoreMouse = ignoreMouse;

		this.components = components;

		this.title = title;

		this.tag = tag;

		this.tag1 = tag1;

		this.tag2 = tag2;

		this.tag3 = tag3;

		this.tag4 = tag4;

		this.tag5 = tag5;

		this.tag6 = tag6;
	}


}




public class PUScrollRectBase : PUGameObject {


	private static Type planetOverride = Type.GetType("PlanetUnityOverride");
	private static MethodInfo processStringMethod = planetOverride.GetMethod("processString", BindingFlags.Public | BindingFlags.Static);




	// XML Attributes
	public bool inertia;
	public bool horizontal;
	public bool vertical;
	public float? scrollWheelSensitivity;




	public override void gaxb_unload()
	{
		base.gaxb_unload();

	}
	
	public new void gaxb_addToParent()

	{
		if(parent != null)
		{
			FieldInfo parentField = parent.GetType().GetField("ScrollRect");
			List<object> parentChildren = null;
			
			if(parentField != null)
			{
				parentField.SetValue(parent, this);
			}
			else
			{
				parentField = parent.GetType().GetField("ScrollRects");
				
				if(parentField != null)
				{
					parentChildren = (List<object>)(parentField.GetValue(parent));
				}
				else
				{
					parentField = parent.GetType().GetField("GameObjects");
					if(parentField != null)
					{
						parentChildren = (List<object>)(parentField.GetValue(parent));
					}
				}
				if(parentChildren == null)
				{
					FieldInfo childrenField = parent.GetType().GetField("children");
					if(childrenField != null)
					{
						parentChildren = (List<object>)childrenField.GetValue(parent);
					}
				}
				if(parentChildren != null)
				{
					parentChildren.Add(this);
				}
				
			}
		}
	}

	public override void gaxb_load(XmlReader reader, object _parent, Hashtable args)
	{
		base.gaxb_load(reader, _parent, args);

		if(reader == null && _parent == null)
			return;
		
		parent = _parent;
		
		if(this.GetType() == typeof( PUScrollRect ))
		{
			gaxb_addToParent();
		}
		
		xmlns = reader.GetAttribute("xmlns");
		

		string attr;
		attr = reader.GetAttribute("inertia");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr == null) { attr = "true"; }
		if(attr != null) { inertia = bool.Parse(attr); } 
		
		attr = reader.GetAttribute("horizontal");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr == null) { attr = "false"; }
		if(attr != null) { horizontal = bool.Parse(attr); } 
		
		attr = reader.GetAttribute("vertical");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr == null) { attr = "true"; }
		if(attr != null) { vertical = bool.Parse(attr); } 
		
		attr = reader.GetAttribute("scrollWheelSensitivity");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr == null) { attr = "0"; }
		if(attr != null) { scrollWheelSensitivity = float.Parse(attr); } 
		

	}
	
	
	
	
	
	
	
	public override void gaxb_appendXMLAttributes(StringBuilder sb)
	{
		base.gaxb_appendXMLAttributes(sb);

		if(inertia != false) { sb.AppendFormat (" {0}=\"{1}\"", "inertia", inertia.ToString().ToLower()); }
		if(horizontal != false) { sb.AppendFormat (" {0}=\"{1}\"", "horizontal", horizontal.ToString().ToLower()); }
		if(vertical != false) { sb.AppendFormat (" {0}=\"{1}\"", "vertical", vertical.ToString().ToLower()); }
		if(scrollWheelSensitivity != null) { sb.AppendFormat (" {0}=\"{1}\"", "scrollWheelSensitivity", scrollWheelSensitivity.Value.ToString ("0.##")); }

	}
	
	public override void gaxb_appendXMLSequences(StringBuilder sb)
	{
		base.gaxb_appendXMLSequences(sb);


	}
	
	public override void gaxb_appendXML(StringBuilder sb)
	{
		if(sb.Length == 0)
		{
			sb.AppendFormat ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		}
		
		sb.AppendFormat ("<{0}", "ScrollRect");
		
		if(xmlns != null)
		{
			sb.AppendFormat (" {0}=\"{1}\"", "xmlns", xmlns);
		}
		
		gaxb_appendXMLAttributes(sb);
		
		
		StringBuilder seq = new StringBuilder();
		seq.AppendFormat(" ");
		gaxb_appendXMLSequences(seq);
		
		if(seq.Length == 1)
		{
			sb.AppendFormat (" />");
		}
		else
		{
			sb.AppendFormat (">{0}</{1}>", seq.ToString(), "ScrollRect");
		}
	}
}
